### ISSUE TITLE
Конвертировать 3 простые html pages в nextjs app

### ISSUE THREAD

**Issue by atherdon** [atherdon/subscribe-form#46]
В этом репозитории есть nodejs script который собирает html из блоков, но это не принципиально сейчас.

нужно сделать 3 страницы, роутер.

чуть позже мы подключим бизнес логику, но сейчас я просто хочу начать этот проект.

в папке HTML сейчас лежат эти страницы.

preview посмотреть.
https://hackernoon.gitlab.io/subscribe-form/good-bye.html
https://hackernoon.gitlab.io/subscribe-form/unsubscribe.html
https://hackernoon.gitlab.io/subscribe-form/subscribe.html

краткий перечень задач
- форк репозитория, 
- посмотреть код страниц, 
- установить nextjs, 
- создать 3 компонента для страниц, 
- создать 2 компонента для форм.
- разбить поля форм на подкомпоненты

**Comment by coder-do** [comment]
@atherdon это всё сделать в папке javascript? Там есть еще код, с этим что сделать плюс он не рабочии, после обновы antd код устарел и не запускается, если там ничего важного, там же создам эти 3 страницы

**Comment by atherdon** [comment]
можно переделать структуру репозитория как захотите @coder-do
