### ISSUE TITLE
re-organize repository structure

### ISSUE THREAD

**Issue by atherdon** [atherdon/subscribe-form#50]
сейчас у нас главное содержимое - это ваш react app код
поэтому этот код должен лежать в root.
все остальное переупакуйте и засуньте в какую то папку(пусть даже это будет папка old)

**Comment by atherdon** [comment]
а я потом смогу подключить репозиторий к heroku и выкладывать ваш код на preview

**Comment by coder-do** [comment]
Этот таск закончили
